#!/usr/bin/env python3

"""
(c) Christoph 'knurd' Morrison, <scripts.idiotcase@christoph-morrison.de>
    2024


This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
"""

from argparse import ArgumentParser
import random

"""

"And all those exclamation marks, you notice? Five? A sure sign of 
someone who wears his underpants on his head."

   -- Terry Pratchett, Maskerade

"""

exclamationMarks = '!!1elf1!'

parser = ArgumentParser(
    prog="idiotcase",
    description='Idotify a given string and adds exclamation marks if wanted',
    epilog='If you are offended by this, gtfo'
)

parser.add_argument('input', help='A string to be idiotied')
parser.add_argument('-e', dest='elf', action='store_true', help='Add exclamtion marks, Pterry style')
args = parser.parse_args()

def idiotcaseify(st):
    ret =[]
    
    for index, character in enumerate(st):
        if random.random() >= 0.49:
            ret.append(character.swapcase())
        else:
            ret.append(character)

    return ''.join(ret)


ret = idiotcaseify(args.input)

if args.elf:
    ret = ret + exclamationMarks

print(ret)